# Generated by Django 5.2.17 on 2026-09-27 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clasificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="código"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=120, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "clasificación",
                "verbose_name_plural": "clasificaciones",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "nacionalidad",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="nacionalidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "director",
                "verbose_name_plural": "directores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "género",
                "verbose_name_plural": "géneros",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="título")),
                (
                    "anio",
                    models.PositiveSmallIntegerField(verbose_name="año de estreno"),
                ),
                (
                    "duracion_min",
                    models.PositiveSmallIntegerField(verbose_name="duración (minutos)"),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="calificación"
                    ),
                ),
                ("sinopsis", models.TextField(verbose_name="sinopsis")),
                (
                    "imagen",
                    models.CharField(
                        blank=True,
                        help_text="Ruta dentro de los archivos estáticos, ej: peliculas/img/coco.svg",
                        max_length=200,
                        verbose_name="imagen",
                    ),
                ),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="peliculas",
                        to="peliculas.clasificacion",
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "directores",
                    models.ManyToManyField(
                        related_name="peliculas",
                        to="peliculas.director",
                        verbose_name="directores",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="peliculas",
                        to="peliculas.genero",
                        verbose_name="género",
                    ),
                ),
            ],
            options={
                "verbose_name": "película",
                "verbose_name_plural": "películas",
                "ordering": ["-anio", "titulo"],
            },
        ),
    ]
