# Generated by Django 5.2.17 on 2026-09-27 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Desarrolladora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "pais",
                    models.CharField(blank=True, max_length=60, verbose_name="país"),
                ),
            ],
            options={
                "verbose_name": "desarrolladora",
                "verbose_name_plural": "desarrolladoras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "género",
                "verbose_name_plural": "géneros",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Plataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="fabricante"
                    ),
                ),
            ],
            options={
                "verbose_name": "plataforma",
                "verbose_name_plural": "plataformas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Videojuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="título")),
                (
                    "anio",
                    models.PositiveSmallIntegerField(verbose_name="año de lanzamiento"),
                ),
                ("precio", models.PositiveIntegerField(verbose_name="precio (CLP)")),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="calificación"
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("E", "E - Todos"),
                            ("E10+", "E10+ - Mayores de 10 años"),
                            ("T", "T - Adolescentes"),
                            ("M", "M - Mayores de 17 años"),
                        ],
                        max_length=5,
                        verbose_name="clasificación ESRB",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "imagen",
                    models.CharField(
                        blank=True,
                        help_text="Ruta dentro de los archivos estáticos, ej: videojuegos/img/zelda.svg",
                        max_length=200,
                        verbose_name="imagen",
                    ),
                ),
                (
                    "desarrolladora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videojuegos",
                        to="videojuegos.desarrolladora",
                        verbose_name="desarrolladora",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videojuegos",
                        to="videojuegos.genero",
                        verbose_name="género",
                    ),
                ),
                (
                    "plataformas",
                    models.ManyToManyField(
                        related_name="videojuegos",
                        to="videojuegos.plataforma",
                        verbose_name="plataformas",
                    ),
                ),
            ],
            options={
                "verbose_name": "videojuego",
                "verbose_name_plural": "videojuegos",
                "ordering": ["titulo"],
            },
        ),
    ]
